### ISSUE TITLE
付费问答删除按钮美化并实现删除提示

### ISSUE THREAD

**Issue by ivanzhang2** [ivanzhang2/haxibiao#10]
.....
如果是付费问题，还需要提醒是已完成回答者的奖金分配，还是0回答已退还奖金

**Comment by ivanzhang2** [comment]
这个feature, 需要前端吕哲哲统一 “我的问题” 列表里的删除按钮  和 问题页面回答的 我的回答下的删除按钮的体验。
后端需要王鑫提供相应的api
最后 产品经理 乐乐需要检验测试，最后乐乐来关闭这个issue吧

**Comment by ivanzhang2** [comment]
更新了下这个issue的标题为：
付费问答删除按钮美化并实现删除提示

**Comment by wangxinaa** [comment]
已经完成

**Comment by jiale888** [comment]
检验测试已完成。关闭issue。
