### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError in GET /xiaocaoyidie

### ISSUE THREAD

**Issue by ivanzhang2** [ivanzhang2/haxibiao#12]
## Error in dongmeiwei.com

**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /xiaocaoyidie**
Call to a member function fillForJs() on null

[View on Bugsnag](https://app.bugsnag.com/haxibiao/dongmeiwei-dot-com/errors/5a97932b6063b20019590018?event_id=5a97932b6063b20019590017&i=gh&m=ci)

## Stacktrace

    app/Article.php:153 - App\Article::fillForJs
    app/Http/Controllers/CategoryController.php:215 - App\Http\Controllers\CategoryController::name_en
    app/Http/Middleware/TrafficMan.php:73 - App\Http\Middleware\TrafficMan::handle
    app/Http/Middleware/CookieChecker.php:24 - App\Http\Middleware\CookieChecker::handle

[View full stacktrace](https://app.bugsnag.com/haxibiao/dongmeiwei-dot-com/errors/5a97932b6063b20019590018?event_id=5a97932b6063b20019590017&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by wangxinaa** [comment]
这是在配置吕哲哲电脑的时候,她的电脑在本地发出的一个error.
