### ISSUE TITLE
蔡志刚 - 完成哈希表爬虫简单管理系统架构的Knowledge Transfer ...

### ISSUE THREAD

**Issue by ivanzhang2** [ivanzhang2/haxibiao#39]
有问题可以后续微信，邮件联系 苏名祁

**Comment by caizhigang1997** [comment]
## 项目结构图
类图:
![uml](https://user-images.githubusercontent.com/36915614/36887204-0a7f4c1a-1e2b-11e8-8239-0f138122c7ee.png)
时序图:          
![default](https://user-images.githubusercontent.com/36915614/36887211-14b66ce0-1e2b-11e8-8284-72d2f3194bd3.png)
## 问题

1. **问题**   根据苏名祁的反馈每当爬取一个分类都需要先建立它的craw_id，有点不好控制。
**解决思路**    尽可能让我们的crawl_*类更通用，保证相同网站复用一套方案(解析, 数据清洗, 入库)。在此基础下，之前我们写的的craw_{id}其实就是每个网站的解析模板，不单单局限于一次解析任务，到时候可能会变成这样：crawl_meishijie(美食杰),crawl_caipudaquan(菜谱大全)。

2. **问题**   按照现在的思路，我们的一次爬取任务是以网站的某个分类为单位来建立的，一般网站分类层级关系太深的话，会建立很多crawl_*。但是为了保证文章抓取回来后索引的方便，子分类不能跳过。
**解决思路**    第一种方案：层级太深的子分类建立tag。第二种方案：通过递归来解决。更加倾向于第二种，建立分类与tag在建立关系以后维护起来会很困难。

3. **问题**   爬虫后台需要通过不断整个页面来获取爬虫的抓取进度，当没有爬虫任务在跑时，也会不断刷新。
**解决思路**   将监听状态变成ajax请求

4. 提高容错机制:有些目标网站,访问会出现各种网络问题，由于我们的爬虫是单线程，当前面的任务出现异常，会导致后面的任务都不能执行成功。 

5.**问题**   断点续传未跑通
**解决思路**   用一个while阻塞，条件为status。

6.**问题**   爬取异常，前台没有提示信息，而是暂停不动。
 **解决思路**  通过ajax来处理

7.其他：有些地方可以抽取的更加通用、前台不能直接触发后台爬取脚本、
