### ISSUE TITLE
懂点医普通用户的投稿功能可以选择的专题有限，也无法收搜专题，出现的专题还是重复的？

### ISSUE THREAD

**Issue by zixin** [ivanzhang2/haxibiao#51]
懂点医普通用户的投稿功能可以选择的专题有限，也无法收搜专题，出现的专题还是重复的？

**Comment by zixin** [comment]
![3](https://user-images.githubusercontent.com/36940213/36956611-4a036c7c-206a-11e8-94a2-aff23eaa57de.jpg)

**Comment by zixin** [comment]
@wangxinaa

**Comment by wangxinaa** [comment]
重复推荐专题已经解决.但是推荐专题那里,需要做成vue吗.简书那里是直接列出所有的系统专题.而不是推荐任何一个人创建的专题吧.

**Comment by zixin** [comment]
我需要直接列出所有的系统的专题，这样可以用户投稿要方便一些，发布了再去投稿有些麻烦。

**Comment by wangxinaa** [comment]
@懂美味已经可以投稿专题,无限加载了. 鼠标滑动加载下一页交给吕哲哲做吧.
