### ISSUE TITLE
懂美味App的详细页正文htmlview高度自动调整还是个问题

### ISSUE THREAD

**Issue by ivanzhang2** [ivanzhang2/haxibiao#52]
这个问题我觉得不用natived的办法估计很难完美实现高度在任何正文html高度的情况下都能完美适应各种系统和设备高度。

附件有个截图说明了，无论如何发现规律，都不能通过js计算得到修改样式后的实际htmlview高度，总是差一些。

<img width="1389" alt="qq20180305-123853 2x" src="https://user-images.githubusercontent.com/13308603/36957963-39062faa-2073-11e8-9c91-b6afe0ec0622.png">

**Comment by ivanzhang2** [comment]
这个issue先挂我和王宇坤头上， 慢慢解决，一定要解决这个问题，才能继续用纯js 解决方案 用expo 开发app，不然需要detach出来用 react-native 开发，编译和部署。

**Comment by ivanzhang2** [comment]
用 https://github.com/archriss/react-native-render-html 来替换Webview了，根据api返回的html, 里面的img 也将通过后台计算好图片的宽高比例，方便前台渲染图片。

这样就能修复html 渲染后高度不确定的情况，每个html 标签都将转换成native 元素来显示。

下面有个视频，演示了修复后的情况

http://haxibiao-1251052432.file.myqcloud.com/mp4/how_to_fix_html-autoheight.mp4

**Comment by yasin-wang** [comment]
好的 我回去研究这个东西的用法

**Comment by ivanzhang2** [comment]
@wangyukun-hxb  我push 了代码： git log hash: 3c6c38d
你拉取后，记得 npm i, restart expo server, 杀掉模拟器内的 expo app, 再 open on 模拟器。

**Comment by yasin-wang** [comment]
拉去代码后detail页面有冲突，解决后点进去报错，应该是个text组件的问题（明天解决）。
