### ISSUE TITLE
群衣阁：问答标签有问题，去掉更多！

### ISSUE THREAD

**Issue by lingxina** [ivanzhang2/haxibiao#57]
![image](https://user-images.githubusercontent.com/36939786/37020234-17b10800-2156-11e8-8cfc-ea8ba0f6c936.png)

**Comment by lingxina** [comment]
有更多，但是应该把涉及的专题用都展示出来，像懂美味这样。
![image](https://user-images.githubusercontent.com/36939786/37020417-a7e4c88a-2156-11e8-86e2-48cbd7c3fd44.png)

**Comment by pengconguses1** [comment]
@leikun222  老雷搞一个页面给我 .

**Comment by pengconguses1** [comment]
已经搞定 .
