### ISSUE TITLE
点默阁问答页面的点赞评论及踩的功能实现

### ISSUE THREAD

**Issue by jiale888** [ivanzhang2/haxibiao#61]
![image](https://user-images.githubusercontent.com/36939886/37070250-97d981a6-21f1-11e8-8a58-c1798e8ad3be.png)
问答主页面的点赞与踩还有分享应该是点赞总数以及踩和评论的总数，点进主页的点赞功能希望能尽快实现。
![image](https://user-images.githubusercontent.com/36939886/37070401-44038350-21f2-11e8-8496-0f9e6870b27a.png)

**Comment by wangxinaa** [comment]
完成了
