### ISSUE TITLE
懂美味发布完页面后续绑定

### ISSUE THREAD

**Issue by jiale888** [ivanzhang2/haxibiao#64]
懂美味编辑器发布后，下面的页面并没有绑定数据，不能点收录或者关注，目前只是一个静态的页面，希望能尽快绑定哟哟哟哟~~~给王鑫笔芯~~~加油~~~你超级棒~~~~
![image](https://user-images.githubusercontent.com/36939886/37081182-9b695b70-2223-11e8-9841-25c4754a4f1f.png)

**Comment by wangxinaa** [comment]
已经完成了.不过最近投稿那部分是假的
