### ISSUE TITLE
群衣阁：评论区的用户头像点不开

### ISSUE THREAD

**Issue by lingxina** [ivanzhang2/haxibiao#65]
![image](https://user-images.githubusercontent.com/36939786/37129642-e971aa88-22ba-11e8-9d6a-188147ae81be.png)

![image](https://user-images.githubusercontent.com/36939786/37129651-f1966622-22ba-11e8-908c-042cdcc49740.png)

**Comment by pengconguses1** [comment]
这个问题已经修复
