### ISSUE TITLE
群衣阁：问答页面有个用户回答、收藏、粉丝的静态假数据，要不就直接去掉。

### ISSUE THREAD

**Issue by lingxina** [ivanzhang2/haxibiao#66]
![image](https://user-images.githubusercontent.com/36939786/37129728-552cbe48-22bb-11e8-81a5-a137e38f0a21.png)

![image](https://user-images.githubusercontent.com/36939786/37129752-6b8d6804-22bb-11e8-8a8e-b089a9748bb1.png)

**Comment by pengconguses1** [comment]
数据是真的 不过数据有误 在修复

**Comment by pengconguses1** [comment]
已经修复
