### ISSUE TITLE
**样式有点不对**

### ISSUE THREAD

**Issue by tanyanqiong** [ivanzhang2/haxibiao#68]
1.搜索栏 搜索之后 网页那个顶端的旅行青蛙可以去掉吗
2.普通用户发文章的编辑器里面能加一个明显的发布和保存草稿按钮吗

**Comment by tanyanqiong** [comment]
![qq 20180308110227](https://user-images.githubusercontent.com/36940246/37130845-56ad80ae-22c0-11e8-93f0-599374ea7085.png)

**Comment by tanyanqiong** [comment]
![qq 20180308110304](https://user-images.githubusercontent.com/36940246/37130879-899052da-22c0-11e8-8efe-17dcba284457.png)
![qq 20180308110326](https://user-images.githubusercontent.com/36940246/37130880-8b35a752-22c0-11e8-9de2-652bdec8b2c4.png)

**Comment by pengconguses1** [comment]
1.第一个问题已经修复.
2.邹敏去看看吧.

**Comment by zoumin-hxb** [comment]
创作页有保存按钮和发布按钮

**Comment by zoumin-hxb** [comment]
为发布按钮添加了四个字
