### ISSUE TITLE
**普通用户发布的文章没有保存**

### ISSUE THREAD

**Issue by tanyanqiong** [ivanzhang2/haxibiao#69]
再回编辑器里面看日记本就只有标题了

**Comment by tanyanqiong** [comment]
![qq 20180308110227](https://user-images.githubusercontent.com/36940246/37130986-2a6ea0b2-22c1-11e8-978c-cd48371098b8.png)

**Comment by pengconguses1** [comment]
这个问题再load一次页面就没问题  应该和请求数据有关
