### ISSUE TITLE
哈希表文章详细页报错

### ISSUE THREAD

**Issue by ivanzhang2** [ivanzhang2/haxibiao#7]
## Error in haxibiao.com

**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /article/382933_2.html**
Call to a member function bodyText() on null

[View on Bugsnag](https://app.bugsnag.com/haxibiao/haxibiao-dot-com/errors/5a96c1613972990019442ff5?event_id=5a975dd7ff3642001a1d8952&i=gh&m=ci)

## Stacktrace

    app/Http/Controllers/ArticleController.php:157 - App\Http\Controllers\ArticleController::show
    app/Http/Middleware/Cors.php:31 - App\Http\Middleware\Cors::handle

[View full stacktrace](https://app.bugsnag.com/haxibiao/haxibiao-dot-com/errors/5a96c1613972990019442ff5?event_id=5a975dd7ff3642001a1d8952&i=gh&m=ci)

*Created by ivan via Bugsnag*

**Comment by ivanzhang2** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /article/382933_2.html**](https://app.bugsnag.com/haxibiao/haxibiao-dot-com/errors/5a96c1613972990019442ff5?event_id=5a975dd7ff3642001a1d8952&i=gh&m=fx)

**Comment by ivanzhang2** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /article/343111_all.html**](https://app.bugsnag.com/haxibiao/haxibiao-dot-com/errors/5a96c1613972990019442ff5?event_id=5a975e9d45ecf20019f4a57d&i=gh&m=ra)

**Comment by ivanzhang2** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /article/55455_4.htm**](https://app.bugsnag.com/haxibiao/haxibiao-dot-com/errors/5a96c1613972990019442ff5?event_id=5a9760dce8ad2800189ed4df&i=gh&m=fx)

**Comment by ivanzhang2** [comment]
还没修复好~

**Comment by ivanzhang2** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**Symfony\Component\Debug\Exception\FatalThrowableError** in **GET /article/55455_4.htm**](https://app.bugsnag.com/haxibiao/haxibiao-dot-com/errors/5a96c1613972990019442ff5?event_id=5a9760dce8ad2800189ed4df&i=gh&m=fx)

**Comment by ivanzhang2** [comment]
reopen

**Comment by pengconguses1** [comment]
这个错误已经修复 现在访问不存在的文章会直接抛出404错误
