### ISSUE TITLE
普通用户的文章发布了之后

### ISSUE THREAD

**Issue by tanyanqiong** [ivanzhang2/haxibiao#70]
不能自己再选主要图 也不能再重新编辑发布了
这个功能要做上去
至少要让他可以自主自己的文章

**Comment by tanyanqiong** [comment]
![default](https://user-images.githubusercontent.com/36940246/37131109-e4bb2300-22c1-11e8-8c87-506eb1a46205.png)

**Comment by pengconguses1** [comment]
这个问题已经修复 普通用户可以编辑自己的文章了
