### ISSUE TITLE
**普通用户发布文章**

### ISSUE THREAD

**Issue by tanyanqiong** [ivanzhang2/haxibiao#72]
数据是乱的
总有一篇没有保存
总会出现两篇无标题文章

**Comment by tanyanqiong** [comment]
![default](https://user-images.githubusercontent.com/36940246/37131454-74159eda-22c3-11e8-81aa-874ef8ef7de1.png)

**Comment by pengconguses1** [comment]
这两篇文章是实际存在的 删除功能有点问题 正在修复

**Comment by pengconguses1** [comment]
已经修复
