### ISSUE TITLE
群衣阁用户头像下喜欢的文章一栏的开发

### ISSUE THREAD

**Issue by lingxina** [ivanzhang2/haxibiao#75]

**Comment by lingxina** [comment]
![image](https://user-images.githubusercontent.com/36939786/37138480-2c2e96b8-22e5-11e8-951b-1c948c6a4cd6.png)

![image](https://user-images.githubusercontent.com/36939786/37138494-39bf5a74-22e5-11e8-8773-3760855243a9.png)

**Comment by pengconguses1** [comment]
@leikun222   老雷 这个页面做了么

**Comment by leikun222** [comment]
已经完成了.
