### ISSUE TITLE
群衣阁：用户改不了头像

### ISSUE THREAD

**Issue by lingxina** [ivanzhang2/haxibiao#78]
![image](https://user-images.githubusercontent.com/36939786/37138857-a8eecc08-22e6-11e8-991c-e641948e776b.png)

**Comment by pengconguses1** [comment]
可以换头像 我测试是可以的

**Comment by lingxina** [comment]
我这边怎么改不了啊？

**Comment by lingxina** [comment]
现在可以了

**Comment by lingxina** [comment]
新注册的用户改不了头像

**Comment by pengconguses1** [comment]
已经修复
