### ISSUE TITLE
群衣阁：问答页面的评论功能还不可以，点赞和踩功能有点问题

### ISSUE THREAD

**Issue by lingxina** [ivanzhang2/haxibiao#79]
![image](https://user-images.githubusercontent.com/36939786/37138960-0b495472-22e7-11e8-9fda-0c98140e6099.png)

**Comment by pengconguses1** [comment]
已经可以评论

**Comment by pengconguses1** [comment]
点赞和踩是编辑允许无限点和踩 我给普通用户加个限制

**Comment by pengconguses1** [comment]
已经修复  只有编辑身份可以无限点赞和踩   普通用户3天内无法对同一个回答点赞
