### ISSUE TITLE
搜索之后 翻页没有标记 不知道自己看到第几页了

### ISSUE THREAD

**Issue by tanyanqiong** [ivanzhang2/haxibiao#83]

**Comment by tanyanqiong** [comment]
![qq 20180319100448](https://user-images.githubusercontent.com/36940246/37574625-274d9e2a-2b5d-11e8-8f91-dc253a68c06c.png)

**Comment by pengconguses1** [comment]
@zoumin-hxb  改一下吧 写这部分vue的时候我忘记加了  现在不知道这个样式在哪

**Comment by zoumin-hxb** [comment]
可以了
